### ISSUE TITLE
Unable to generate refresh token - KeyError: 'PROVIDE_AUTOMATIC_OPTIONS

### ISSUE THREAD

**Issue by khadanja** [TheCaduceus/Microsoft-E5-Auto-Renewal#26]
Getting this as soon as I run python auth.py locally. Worked few months back.
app.py.py", line 5, in <module>
    app = Quart(__name__)
          ^^^^^^^^^^^^^^^
AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\sansio\app.py", line 641, in add_url_rule
    if "OPTIONS" not in methods and self.config["PROVIDE_AUTOMATIC_OPTIONS"]:
                                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PROVIDE_AUTOMATIC_OPTIONS'

**Comment by TheCaduceus** [comment]
Hi, looks like Quart recently pushed breaking changes which causing this issue. This can be fixed by degrading installed Quart version by running following command:
`pip install quart==0.19.6`

or mention it in `requirements.txt` file:
`quart==0.19.6`

@khadanja

**Comment by khadanja** [comment]
@TheCaduceus  Thanks for replying, same issue with 0.19.6
Downloading quart-0.19.6-py3-none-any.whl (78 kB)
Installing collected packages: quart
  Attempting uninstall: quart
    Found existing installation: Quart 0.19.8
    Uninstalling Quart-0.19.8:
      Successfully uninstalled Quart-0.19.8
Successfully installed quart-0.19.6

**Comment by khadanja** [comment]
@TheCaduceus  Fixed by adding this to requirements.txt flask==3.0.3 Quart downgrade not required.
https://github.com/pallets/quart/issues/371

**Comment by TheCaduceus** [comment]
Recently, Flask released a breaking update about 12 hours ago, and since Quart uses Flask without locking its version, this caused an issue (https://github.com/pallets/quart/issues/371) in Quart for everyone. For now, I have manually locked all dependency versions to resolve the issue.

You can update your `requirements.txt` file's content with [this](https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/commit/f3417d6ce8b8ac8d3b8779ddcbfd39014c931e10) and do:
1.`pip uninstall -r requirements.txt`
2.`pip install -r requirements.txt`

@khadanja

**Comment by khadanja** [comment]
Thanks @TheCaduceus  I created a PR but looks like you've updated already, will close my PR. Thanks
